"""GeneratedBarcode model — registry of locally generated EAN-13 barcodes."""
from datetime import datetime
from typing import Optional
from sqlalchemy import String, DateTime
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base


class GeneratedBarcode(Base):
    """
    Registry of EAN-13 barcodes generated by the application.
    
    Ensures global uniqueness — no barcode is ever reused.
    Uses prefix '200' for internal/variable-weight items (no GS1 membership needed).
    """
    __tablename__ = "generated_barcodes"

    id: Mapped[int] = mapped_column(primary_key=True)
    barcode: Mapped[str] = mapped_column(String(13), unique=True, index=True)
    sku: Mapped[Optional[str]] = mapped_column(String(100), nullable=True, index=True)
    product_uid: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    assigned_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
